ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of THDM_type1_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_67 = ', GC_67
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_87 = ', GC_87
      WRITE(*,2) 'GC_127 = ', GC_127
      WRITE(*,2) 'GC_141 = ', GC_141
      WRITE(*,2) 'GC_142 = ', GC_142
      WRITE(*,2) 'GC_145 = ', GC_145
      WRITE(*,2) 'GC_146 = ', GC_146
      WRITE(*,2) 'GC_157 = ', GC_157
      WRITE(*,2) 'GC_165 = ', GC_165
      WRITE(*,2) 'GC_169 = ', GC_169
      WRITE(*,2) 'GC_173 = ', GC_173
      WRITE(*,2) 'GC_181 = ', GC_181
