ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_l2 = ', MDL_L2
      WRITE(*,*) 'mdl_l3 = ', MDL_L3
      WRITE(*,*) 'mdl_lR7 = ', MDL_LR7
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymdo = ', MDL_YMDO
      WRITE(*,*) 'mdl_ymup = ', MDL_YMUP
      WRITE(*,*) 'mdl_yms = ', MDL_YMS
      WRITE(*,*) 'mdl_ymc = ', MDL_YMC
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_yme = ', MDL_YME
      WRITE(*,*) 'mdl_ymm = ', MDL_YMM
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_TB = ', MDL_TB
      WRITE(*,*) 'mdl_sinbma = ', MDL_SINBMA
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_Me = ', MDL_ME
      WRITE(*,*) 'mdl_MMU = ', MDL_MMU
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MU = ', MDL_MU
      WRITE(*,*) 'mdl_MC = ', MDL_MC
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MD = ', MDL_MD
      WRITE(*,*) 'mdl_MS = ', MDL_MS
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_mhc = ', MDL_MHC
      WRITE(*,*) 'mdl_mh1 = ', MDL_MH1
      WRITE(*,*) 'mdl_mh2 = ', MDL_MH2
      WRITE(*,*) 'mdl_mh3 = ', MDL_MH3
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_whc = ', MDL_WHC
      WRITE(*,*) 'mdl_Wh1 = ', MDL_WH1
      WRITE(*,*) 'mdl_Wh2 = ', MDL_WH2
      WRITE(*,*) 'mdl_Wh3 = ', MDL_WH3
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_TB__exp__2 = ', MDL_TB__EXP__2
      WRITE(*,*) 'mdl_CB = ', MDL_CB
      WRITE(*,*) 'mdl_sinbma__exp__2 = ', MDL_SINBMA__EXP__2
      WRITE(*,*) 'mdl_cosbma = ', MDL_COSBMA
      WRITE(*,*) 'mdl_l7 = ', MDL_L7
      WRITE(*,*) 'mdl_lI5 = ', MDL_LI5
      WRITE(*,*) 'mdl_lI6 = ', MDL_LI6
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_CB__exp__2 = ', MDL_CB__EXP__2
      WRITE(*,*) 'mdl_SB = ', MDL_SB
      WRITE(*,*) 'mdl_CA = ', MDL_CA
      WRITE(*,*) 'mdl_CA__exp__2 = ', MDL_CA__EXP__2
      WRITE(*,*) 'mdl_SA = ', MDL_SA
      WRITE(*,*) 'mdl_mhc__exp__2 = ', MDL_MHC__EXP__2
      WRITE(*,*) 'mdl_mh1__exp__2 = ', MDL_MH1__EXP__2
      WRITE(*,*) 'mdl_mh2__exp__2 = ', MDL_MH2__EXP__2
      WRITE(*,*) 'mdl_mh3__exp__2 = ', MDL_MH3__EXP__2
      WRITE(*,*) 'mdl_asin__sinbma = ', MDL_ASIN__SINBMA
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_cosbma__exp__2 = ', MDL_COSBMA__EXP__2
      WRITE(*,*) 'mdl_cosbma__exp__4 = ', MDL_COSBMA__EXP__4
      WRITE(*,*) 'mdl_cosbma__exp__3 = ', MDL_COSBMA__EXP__3
      WRITE(*,*) 'mdl_sinbma__exp__3 = ', MDL_SINBMA__EXP__3
      WRITE(*,*) 'mdl_sinbma__exp__4 = ', MDL_SINBMA__EXP__4
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_mu2 = ', MDL_MU2
      WRITE(*,*) 'mdl_l1 = ', MDL_L1
      WRITE(*,*) 'mdl_l4 = ', MDL_L4
      WRITE(*,*) 'mdl_lR5 = ', MDL_LR5
      WRITE(*,*) 'mdl_lR6 = ', MDL_LR6
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yc = ', MDL_YC
      WRITE(*,*) 'mdl_ydo = ', MDL_YDO
      WRITE(*,*) 'mdl_ye = ', MDL_YE
      WRITE(*,*) 'mdl_ym = ', MDL_YM
      WRITE(*,*) 'mdl_ys = ', MDL_YS
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_yup = ', MDL_YUP
      WRITE(*,*) 'mdl_mu1 = ', MDL_MU1
      WRITE(*,*) 'mdl_l5 = ', MDL_L5
      WRITE(*,*) 'mdl_l6 = ', MDL_L6
      WRITE(*,*) 'mdl_mu3 = ', MDL_MU3
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*) 'mdl_sw__exp__3 = ', MDL_SW__EXP__3
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
