.gcc_setup: &gcc_setup
  image: gcc:9
  before_script:
    - apt-get update
    - apt-get install -y cmake doxygen graphviz python3-pandas python3-numpy python3-pytest

build:gcc:
  <<: *gcc_setup
  stage: build
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_Fortran_FLAGS='-Werror -fimplicit-none -fcheck=all' ..
    - make
  artifacts:
    paths:
      - build
    expire_in: 1 hour
  tags:
    - docker

test:gcc:
  <<: *gcc_setup
  stage: test
  script:
    - cd build
    - ctest --output-on-failure
  tags:
    - docker
  needs:
    - build:gcc

HBAnalyses:generate:
  stage: test
  image: gcc:9
  needs:
    - build:gcc
  before_script:
    - apt-get update && apt-get install -y python3-requests
  script:
    - mkdir build/bib && cd build/bib
    - cp ../../doc/bib/HBnumeric.bbx HBnumeric.bbx
    - python3 ../../doc/bib/HBAnalyses.py
  artifacts:
    paths:
      - build/bib/*
    expire_in: 1 hour

HBAnalyses:
  stage: deploy
  image: makisyu/texlive-2016
  needs:
    - HBAnalyses:generate
  script:
    - mv build/bib HBAnalyses
    - cd HBAnalyses
    - latexmk -pdf HBAnalyses
  artifacts:
    paths:
      - HBAnalyses/HBAnalyses.tex
      - HBAnalyses/HBAnalyses.bib
      - HBAnalyses/HBAnalyses.pdf
      - HBAnalyses/HBAnalyses.txt
      - HBAnalyses/HBnumeric.bbx
  only:
    - master

pages:
  stage: deploy
  <<: *gcc_setup
  dependencies:
    - build:gcc
  script:
    - apt-get install -y libjs-mathjax
    - cd build
    - cmake -DDOXYGEN_MATHJAX_RELPATH='mathjax' ..
    - make doc
    - mv doc/html/ ../public/
    - cp -r /usr/share/javascript/mathjax/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
